# Generated by Django 2.2.19 on 2021-04-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210404_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumuser',
            name='is_basic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
