# Generated by Django 2.2.17 on 2021-03-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210323_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeoverview',
            name='directions',
            field=models.TextField(max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='recipeoverview',
            name='ingredients',
            field=models.TextField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='recipeoverview',
            name='title',
            field=models.TextField(max_length=1000),
        ),
    ]
