# Generated by Django 2.2.17 on 2021-03-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='id',
            new_name='even_id',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='name',
            new_name='event_name',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='start',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='events',
            name='event_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
