# Generated by Django 2.2.17 on 2021-03-24 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210324_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='even_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='event_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='start_date',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_type',
        ),
    ]
