# Generated by Django 2.2.17 on 2021-03-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210324_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
