# Generated by Django 2.2.17 on 2021-03-24 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_events_mealposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='mealChosen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.RecipeOverview'),
        ),
    ]
