# Generated by Django 2.2.19 on 2021-03-27 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_events_mealchosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='mealChosen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal', to='recipes.RecipeOverview'),
        ),
    ]
