# Generated by Django 2.2.19 on 2021-03-27 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20210327_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='mealChosen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.RecipeOverview'),
        ),
    ]
