# Generated by Django 2.2.19 on 2021-03-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20210327_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='feedbackGiven',
            field=models.BooleanField(default=False),
        ),
    ]
