# Generated by Django 2.2.19 on 2021-03-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_shoppinglist_shoppinglistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
