# Generated by Django 2.2.19 on 2021-03-27 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_auto_20210327_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='user',
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Ingredient'),
        ),
    ]
