# Generated by Django 2.2.19 on 2021-03-27 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_auto_20210327_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='user',
        ),
    ]
