# Generated by Django 2.2.19 on 2021-03-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_remove_shoppinglist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeoverview',
            name='cookingMins',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recipeoverview',
            name='highCalories',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipeoverview',
            name='highCarbs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipeoverview',
            name='highFat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipeoverview',
            name='highProtein',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipeoverview',
            name='lowCarbs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipeoverview',
            name='mealTypes',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recipeoverview',
            name='percentCalories',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='recipeoverview',
            name='percentCarbs',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='recipeoverview',
            name='percentFat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='recipeoverview',
            name='percentProtein',
            field=models.FloatField(null=True),
        ),
    ]
