# Generated by Django 2.2.19 on 2021-03-28 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0021_auto_20210328_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayIntensity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('intensity', models.CharField(choices=[('rest', 'Rest'), ('easy', 'Easy'), ('workout', 'Workout'), ('all_out', 'All_Out')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
