# Generated by Django 2.2.19 on 2021-03-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20210327_1646'),
        ('recipes', '0022_dayintensity'),
    ]

    operations = [
    ]
