# Generated by Django 2.2.17 on 2021-01-18 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekplan',
            name='day1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='day1', to='core.DayNeeds'),
        ),
        migrations.AlterField(
            model_name='weekplan',
            name='day2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='day2', to='core.DayNeeds'),
        ),
        migrations.AlterField(
            model_name='weekplan',
            name='day3',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='day3', to='core.DayNeeds'),
        ),
        migrations.AlterField(
            model_name='weekplan',
            name='day4',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='day4', to='core.DayNeeds'),
        ),
        migrations.AlterField(
            model_name='weekplan',
            name='day5',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='day5', to='core.DayNeeds'),
        ),
        migrations.AlterField(
            model_name='weekplan',
            name='day6',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='day6', to='core.DayNeeds'),
        ),
        migrations.AlterField(
            model_name='weekplan',
            name='day7',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='day7', to='core.DayNeeds'),
        ),
    ]
