# Generated by Django 2.2.17 on 2021-01-18 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_weekdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekdays',
            name='day1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d1', to='core.DayNeeds'),
        ),
        migrations.AlterField(
            model_name='weekdays',
            name='day2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d2', to='core.DayNeeds'),
        ),
        migrations.AlterField(
            model_name='weekdays',
            name='day3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d3', to='core.DayNeeds'),
        ),
        migrations.AlterField(
            model_name='weekdays',
            name='day4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d4', to='core.DayNeeds'),
        ),
        migrations.AlterField(
            model_name='weekdays',
            name='day5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d5', to='core.DayNeeds'),
        ),
        migrations.AlterField(
            model_name='weekdays',
            name='day6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d6', to='core.DayNeeds'),
        ),
        migrations.AlterField(
            model_name='weekdays',
            name='day7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d7', to='core.DayNeeds'),
        ),
    ]
