# Generated by Django 2.2.17 on 2021-01-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210118_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spoonApi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='spoonHash',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
