# Generated by Django 2.2.17 on 2021-01-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210118_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='spoonApi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='spoonHash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
