# Generated by Django 2.2.19 on 2021-03-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210118_2108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredient',
            new_name='IngredientSpoon',
        ),
    ]
